# Generated by Django 4.2 on 2025-02-22 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_number', models.CharField(max_length=255, unique=True)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=255)),
                ('estimated_ready_time', models.DateTimeField(blank=True, null=True)),
                ('customer_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendors')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Status_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
            ],
        ),
    ]
