# Generated by Django 4.2 on 2025-02-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='customer_phone_number',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='estimated_ready_time',
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='orders',
            name='token_number',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
