# Generated by Django 4.2 on 2025-02-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_location', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_information', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
